// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactAspNetApp.Data;

#nullable disable

namespace ReactAspNetApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250916021802_AddProcurementFields")]
    partial class AddProcurementFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReactAspNetApp.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AssetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Floor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwnedByCounty")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObjectCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<int>("ReceivableReportId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("CountyCode");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ObjectCode");

                    b.HasIndex("ReceivableReportId");

                    b.HasIndex("SerialNumber");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTag = "DL-7420-001",
                            AssetValue = 1200.00m,
                            AssignedTo = "John Doe",
                            Brand = "Dell",
                            CreatedBy = "John Smith",
                            CreatedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "2",
                            IsDeleted = false,
                            IsOwnedByCounty = false,
                            Make = "Latitude",
                            Model = "7420",
                            ObjectCode = "OBJ001",
                            ReceivableReportId = 1,
                            Room = "201A",
                            SerialNumber = "SN123456789"
                        },
                        new
                        {
                            Id = 2,
                            AssetTag = "HP-840-001",
                            AssetValue = 1100.00m,
                            AssignedTo = "Jane Smith",
                            Brand = "HP",
                            CountyCode = "CTY001",
                            CreatedBy = "John Smith",
                            CreatedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "2",
                            IsDeleted = false,
                            IsOwnedByCounty = true,
                            Make = "EliteBook",
                            Model = "840 G8",
                            ObjectCode = "OBJ001",
                            ReceivableReportId = 1,
                            Room = "202B",
                            SerialNumber = "SN987654321"
                        },
                        new
                        {
                            Id = 3,
                            AssetTag = "HM-CHAIR-001",
                            AssetValue = 800.00m,
                            AssignedTo = "Bob Johnson",
                            Brand = "Herman Miller",
                            CreatedBy = "Jane Doe",
                            CreatedDate = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "1",
                            IsDeleted = false,
                            IsOwnedByCounty = false,
                            Make = "Aeron",
                            Model = "Chair",
                            ObjectCode = "OBJ002",
                            ReceivableReportId = 2,
                            Room = "101",
                            SerialNumber = "CH123456789"
                        },
                        new
                        {
                            Id = 4,
                            AssetTag = "CS-2960X-001",
                            AssetValue = 2500.00m,
                            AssignedTo = "Network Team",
                            Brand = "Cisco",
                            CountyCode = "CTY002",
                            CreatedBy = "Jane Doe",
                            CreatedDate = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "B1",
                            IsDeleted = false,
                            IsOwnedByCounty = true,
                            Make = "Catalyst",
                            Model = "2960X",
                            ObjectCode = "OBJ004",
                            ReceivableReportId = 2,
                            Room = "Server Room",
                            SerialNumber = "NW987654321"
                        },
                        new
                        {
                            Id = 5,
                            AssetTag = "AP-IP14-001",
                            AssetValue = 999.00m,
                            AssignedTo = "Marketing Team",
                            Brand = "Apple",
                            CreatedBy = "Mike Johnson",
                            CreatedDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "3",
                            IsDeleted = false,
                            IsOwnedByCounty = false,
                            Make = "iPhone",
                            Model = "14 Pro",
                            ObjectCode = "OBJ005",
                            ReceivableReportId = 3,
                            Room = "301",
                            SerialNumber = "MB123456789"
                        },
                        new
                        {
                            Id = 6,
                            AssetTag = "MS-SL5-001",
                            AssetValue = 1300.00m,
                            AssignedTo = "Executive Team",
                            Brand = "Microsoft",
                            CountyCode = "CTY004",
                            CreatedBy = "Sarah Wilson",
                            CreatedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "4",
                            IsDeleted = false,
                            IsOwnedByCounty = true,
                            Make = "Surface",
                            Model = "Laptop 5",
                            ObjectCode = "OBJ001",
                            ReceivableReportId = 4,
                            Room = "Executive Suite",
                            SerialNumber = "SL987654321"
                        },
                        new
                        {
                            Id = 7,
                            AssetTag = "CN-PP100-001",
                            AssetValue = 350.00m,
                            AssignedTo = "Design Team",
                            Brand = "Canon",
                            CreatedBy = "Sarah Wilson",
                            CreatedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "3",
                            IsDeleted = false,
                            IsOwnedByCounty = false,
                            Make = "PIXMA",
                            Model = "Pro-100",
                            ObjectCode = "OBJ006",
                            ReceivableReportId = 4,
                            Room = "Design Lab",
                            SerialNumber = "PR123456789"
                        });
                });

            modelBuilder.Entity("ReactAspNetApp.Models.AssetHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AssetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CountyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Floor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("HistoryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HistoryUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwnedByCounty")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObjectCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OriginalCreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OriginalCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OriginalModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceivableReportId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HistoryId");

                    b.HasIndex("AssetId");

                    b.HasIndex("HistoryDate");

                    b.HasIndex("OperationType");

                    b.ToTable("AssetHistory", t =>
                        {
                            t.HasCheckConstraint("CK_AssetHistory_OperationType", "[OperationType] IN ('INSERT', 'UPDATE', 'DELETE')");
                        });
                });

            modelBuilder.Entity("ReactAspNetApp.Models.County", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Code");

                    b.HasIndex("Name", "State")
                        .IsUnique();

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            Code = "CTY001",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "New York County",
                            State = "NY"
                        },
                        new
                        {
                            Code = "CTY002",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Los Angeles County",
                            State = "CA"
                        },
                        new
                        {
                            Code = "CTY003",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Cook County",
                            State = "IL"
                        },
                        new
                        {
                            Code = "CTY004",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Harris County",
                            State = "TX"
                        },
                        new
                        {
                            Code = "CTY005",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Maricopa County",
                            State = "AZ"
                        },
                        new
                        {
                            Code = "CTY006",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Miami-Dade County",
                            State = "FL"
                        });
                });

            modelBuilder.Entity("ReactAspNetApp.Models.Location", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Code");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Code = "LOC001",
                            AddressLine1 = "123 Main Street",
                            City = "New York",
                            Country = "USA",
                            County = "New York County",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PostalCode = "10001",
                            State = "NY"
                        },
                        new
                        {
                            Code = "LOC002",
                            AddressLine1 = "456 Oak Avenue",
                            City = "Los Angeles",
                            Country = "USA",
                            County = "Los Angeles County",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PostalCode = "90210",
                            State = "CA"
                        },
                        new
                        {
                            Code = "LOC003",
                            AddressLine1 = "789 Chicago Blvd",
                            City = "Chicago",
                            Country = "USA",
                            County = "Cook County",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PostalCode = "60601",
                            State = "IL"
                        },
                        new
                        {
                            Code = "LOC004",
                            AddressLine1 = "321 Houston Street",
                            City = "Houston",
                            Country = "USA",
                            County = "Harris County",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PostalCode = "77001",
                            State = "TX"
                        });
                });

            modelBuilder.Entity("ReactAspNetApp.Models.ObjectCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObjectCodes");

                    b.HasData(
                        new
                        {
                            Code = "OBJ001",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Desktop computers, laptops, servers",
                            IsActive = true,
                            Name = "Computer Equipment"
                        },
                        new
                        {
                            Code = "OBJ002",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Desks, chairs, filing cabinets",
                            IsActive = true,
                            Name = "Office Furniture"
                        },
                        new
                        {
                            Code = "OBJ003",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Software applications and licenses",
                            IsActive = true,
                            Name = "Software License"
                        },
                        new
                        {
                            Code = "OBJ004",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Routers, switches, access points",
                            IsActive = true,
                            Name = "Network Equipment"
                        },
                        new
                        {
                            Code = "OBJ005",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phones, tablets, mobile accessories",
                            IsActive = true,
                            Name = "Mobile Devices"
                        },
                        new
                        {
                            Code = "OBJ006",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cameras, projectors, audio systems",
                            IsActive = true,
                            Name = "Audio/Video Equipment"
                        });
                });

            modelBuilder.Entity("ReactAspNetApp.Models.Organization", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Code = "ORG001",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 9, 16, 2, 18, 2, 278, DateTimeKind.Utc).AddTicks(9420),
                            IsActive = true,
                            Name = "Technology Department"
                        },
                        new
                        {
                            Code = "ORG002",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 9, 16, 2, 18, 2, 278, DateTimeKind.Utc).AddTicks(9422),
                            IsActive = true,
                            Name = "Finance Department"
                        },
                        new
                        {
                            Code = "ORG003",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 9, 16, 2, 18, 2, 278, DateTimeKind.Utc).AddTicks(9424),
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Code = "ORG004",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 9, 16, 2, 18, 2, 278, DateTimeKind.Utc).AddTicks(9426),
                            IsActive = true,
                            Name = "Operations Department"
                        });
                });

            modelBuilder.Entity("ReactAspNetApp.Models.ReceivableReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AttestedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("AttestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ChargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<string>("PcardHolderFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PcardHolderLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProcurementType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LocationCode");

                    b.HasIndex("OrderStatus");

                    b.HasIndex("OrganizationCode");

                    b.ToTable("ReceivableReports", t =>
                        {
                            t.HasCheckConstraint("CK_ReceivableReport_OrderStatus", "[OrderStatus] IN ('Partial', 'Complete')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "123 Main Street",
                            City = "New York",
                            County = "New York County",
                            CreatedBy = "John Smith",
                            CreatedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LocationCode = "LOC001",
                            OrderStatus = "Partial",
                            OrganizationCode = "ORG001",
                            PostalCode = "10001",
                            State = "NY"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "456 Oak Avenue",
                            City = "Los Angeles",
                            CompletedBy = "Jane Doe",
                            CompletedDate = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            County = "Los Angeles County",
                            CreatedBy = "Jane Doe",
                            CreatedDate = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LocationCode = "LOC002",
                            OrderStatus = "Complete",
                            OrganizationCode = "ORG002",
                            PostalCode = "90210",
                            State = "CA"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "789 Chicago Blvd",
                            City = "Chicago",
                            County = "Cook County",
                            CreatedBy = "Mike Johnson",
                            CreatedDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LocationCode = "LOC003",
                            OrderStatus = "Partial",
                            OrganizationCode = "ORG003",
                            PostalCode = "60601",
                            State = "IL"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine1 = "321 Houston Street",
                            AttestedBy = "Admin User",
                            AttestedDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            City = "Houston",
                            CompletedBy = "Sarah Wilson",
                            CompletedDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            County = "Harris County",
                            CreatedBy = "Sarah Wilson",
                            CreatedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LocationCode = "LOC004",
                            OrderStatus = "Complete",
                            OrganizationCode = "ORG001",
                            PostalCode = "77001",
                            State = "TX"
                        });
                });

            modelBuilder.Entity("ReactAspNetApp.Models.ReceivableReportHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AttestedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("AttestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HistoryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HistoryUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OriginalCreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OriginalCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OriginalModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ReceivableReportId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("HistoryId");

                    b.HasIndex("HistoryDate");

                    b.HasIndex("OperationType");

                    b.HasIndex("ReceivableReportId");

                    b.ToTable("ReceivableReportHistory", t =>
                        {
                            t.HasCheckConstraint("CK_ReceivableReportHistory_OperationType", "[OperationType] IN ('INSERT', 'UPDATE', 'DELETE')");
                        });
                });

            modelBuilder.Entity("ReactAspNetApp.Models.Asset", b =>
                {
                    b.HasOne("ReactAspNetApp.Models.County", "County")
                        .WithMany("Assets")
                        .HasForeignKey("CountyCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReactAspNetApp.Models.ObjectCode", "ObjectCodeNavigation")
                        .WithMany("Assets")
                        .HasForeignKey("ObjectCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReactAspNetApp.Models.ReceivableReport", "ReceivableReport")
                        .WithMany("Assets")
                        .HasForeignKey("ReceivableReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");

                    b.Navigation("ObjectCodeNavigation");

                    b.Navigation("ReceivableReport");
                });

            modelBuilder.Entity("ReactAspNetApp.Models.ReceivableReport", b =>
                {
                    b.HasOne("ReactAspNetApp.Models.Location", "Location")
                        .WithMany("ReceivableReports")
                        .HasForeignKey("LocationCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReactAspNetApp.Models.Organization", "Organization")
                        .WithMany("ReceivableReports")
                        .HasForeignKey("OrganizationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ReactAspNetApp.Models.County", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ReactAspNetApp.Models.Location", b =>
                {
                    b.Navigation("ReceivableReports");
                });

            modelBuilder.Entity("ReactAspNetApp.Models.ObjectCode", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ReactAspNetApp.Models.Organization", b =>
                {
                    b.Navigation("ReceivableReports");
                });

            modelBuilder.Entity("ReactAspNetApp.Models.ReceivableReport", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
